name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t krukalex/react-test -f ./client/Dockerfile.dev ./client
      # - run: docker run -e CI=true -w /app krukalex/react-test npm test

      - run: docker build -t krukalex/multi-client ./client
      - run: docker build -t krukalex/multi-nginx ./nginx
      - run: docker build -t krukalex/multi-server ./server
      - run: docker build -t krukalex/multi-worker ./worker

      - run: docker push krukalex/multi-client
      - run: docker push krukalex/multi-nginx
      - run: docker push krukalex/multi-server
      - run: docker push krukalex/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-545746120737
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
