name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - run: docker build -t krukalex/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true krukalex/react-test npm test

      - run: docker build -t krukalex/multi-client ./client
      - run: docker build -t krukalex/multi-nginx ./nginx
      - run: docker build -t krukalex/multi-server ./server
      - run: docker build -t krukalex/multi-worker ./worker

      - run: docker push krukalex/multi-client
      - run: docker push krukalex/multi-nginx
      - run: docker push krukalex/multi-server
      - run: docker push krukalex/multi-worker
